services:
  nginx_proxy:
    image: nginx
    container_name: nginx_proxy
    ports:
      - '80:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - web_server
    networks:
      - internet
      - localnet

  web_server:
    build: ../part_5
    container_name: web_server
    ports:
      - '8080:81'
    restart: unless-stopped
    networks:
      - localnet

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
    internal: true